language: c
os:
  - linux
script: autoreconf -i && ./configure && make all check
addons:
  apt:
    packages:
      - xmlto
      - libtest-most-perl
      - libtest-output-perl

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: trusty
      env: MATRIX_EVAL="CC=gcc"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - xmlto
            - libtest-most-perl
            - libtest-output-perl
      compiler: gcc
      dist: trusty
      env: MATRIX_EVAL="CC=gcc-7"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - xmlto
            - libtest-most-perl
            - libtest-output-perl
      compiler: gcc
      dist: trusty
      env: MATRIX_EVAL="CC=gcc-8"

before_install:
  - export "${MATRIX_EVAL}"

