language: c
os:
  - linux
script: make all check
addons:
  apt:
    packages:
      - xmlto

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
      compiler: gcc
      dist: trusty
      env: MATRIX_EVAL="CC=gcc-7"

before_install:
  - test -v MATRIX_EVAL && export "${MATRIX_EVAL}"

