name: Build and test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        image: ["fedora:latest", "fedora:rawhide"]
    container:
      image: ${{ matrix.image }}
    steps:
    - uses: actions/checkout@v2
    - run: sudo yum install -y /usr/bin/prove openssl autoconf aclocal gcc make openssl-devel 
                               'perl(Test::Output)' 'perl(File::Temp)' 'perl(Time::Local)'
                               'perl(Test)' /usr/bin/xmlto
    - run: autoreconf -Wall
    - run: ./configure --prefix=/tmp/cadaver-root 
    - run: make
    - run: make check
    - run: make install
